### ISSUE TITLE
Add rustfmt.toml

### ISSUE THREAD

**Issue by leifhelm** [reitermarkus/dlms-cosem-rs#13]
Hi,
could you please add your `rustfmt.toml` file. This would make future development more consistent and easier.
Maybe also add a CI pipeline that checks source code formatting.
BR

**Comment by reitermarkus** [comment]
I usually don't use `rustfmt` because it sometimes makes weird choices you cannot opt-out of. Since I haven't used it in a while, maybe now there's a way now to opt out of certain things.

I'll have a look at what the current state is.

**Comment by leifhelm** [comment]
Have a look at the [config options](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=)

**Comment by reitermarkus** [comment]
@leifhelm, yeah, I am aware of the options, the problem I have with it is that you cannot opt out of options completely, i.e. you have to choose one variant of each option but you cannot disable an option entirely.
